add cleanup logic and process management in staging.yml

diff --git a/.github/workflows/staging.yml b/.github/workflows/staging.yml
--- a/.github/workflows/staging.yml
+++ b/.github/workflows/staging.yml
@@ -158,18 +158,37 @@ jobs:
           key: ${{ secrets.REMOTE_SSH_KEY }}
           script: |
             #!/bin/bash
+            ## catch the exit code & apply logic accordingly
+            function finish() {
+              rv=$?
+              echo "the error code received is $rv"
+              if [ $rv -eq 137 ];
+              then
+                echo "It's a manual kill, attempting another run or whatever"
+              elif [ $rv -eq 0 ];
+                then
+                echo "Exited smoothly"
+              else
+                echo "Non 0 & 137 exit codes"
+                exit $rv
+              fi
+            }
+  
             docker stop postgres_staging || true
             docker rm postgres_staging || true
             echo starting postgres
             docker run -d --name postgres_staging -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_STAGING_KEY }} -e POSTGRES_DB=flumip_staging -v flumip_staging_data:/var/lib/postgresql/data -p 5433:5432 --restart unless-stopped postgres:16.3
-            echo getting pid
-            pid=$(pgrep -f "\./server --mode=staging")
-            echo killing $pid
-            if [ -n "$pid" ]; then
-              echo pid is $pid
-              kill "$pid" || true
+            echo "getting pid"
+            pgrep -f "\./server --mode=staging"
+            if [ $? -eq 0 ];
+            then
+              echo "Killing the previous server process"
+              kill -9 $(pgrep -f "\./server --mode=staging")
+            else
+              echo "No previous server process exists."
             fi
-            echo removing old backend
+            trap finish EXIT
+            echo "removing old backend"
             rm -rf /var/www/flumip_staging/backend
             mv ~/flumip_staging/backend/flumip_server/app /var/www/flumip_staging/backend
             cd /var/www/flumip_staging/backend
